config/routes.rb
Rails.application.routes.draw do
  root "toppages#index"

	get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

	get 'signup', to: 'users#new'
	resources :users, only: [:index,:show, :new, :create, :edit, :update, :destroy] do
	  member do
      get :followings
      get :followers

      get :likes
    end
	end

	resources :posts, only: [:show, :new, :edit, :create, :update, :destroy] do
	  resources :comments, only: [:create, :destroy]
	end

  resources :relationships, only: [:create, :destroy]

  resources :likes, only: [:create, :destroy]


end

app/models/user.rb
class User < ApplicationRecord
	before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
	has_secure_password

#退会時に全投稿を削除する=========================================
  has_many :posts, :dependent => :destroy
#プロフィール画像登録=========================================
  #has_one_attachedは一個のファイルを添付するための属性モデルクラス
  #attributeはモデルに読み書き可能な属性を追加します

  mount_uploader :image, ImageUploader


#プロフィール画像削除=========================================


#投稿機能========================================================
  has_many :posts

  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverses_of_relationship, source: :user

#フォロー機能========================================================
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

#お気に入り========================================================
  has_many :likes
  has_many :likings, through: :likes, source: :post

  def like(other_post)
      self.likes.find_or_create_by(post_id: other_post.id)
  end

  def unlike(other_post)
    like = self.likes.find_by(post_id: other_post.id)
    like.destroy if like
  end

  def liking?(other_post)
    self.likings.include?(other_post)
  end

#コメント機能========================================================
  has_many :comments

#ユーザー検索機能========================================================
  def self.search(search) #ここでのself.はUser.を意味する
    if search
      where(['name LIKE ?', "%#{search}%"]) #検索とnameの部分一致を表示
    else
      all #全て表示。#User.は省略
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index,:show, :followings, :followers, :likes, :edit, :update, :destroy]

  def index
    @users = User.order(id: :desc).page(params[:page]).per(25).where('name LIKE ?', "%#{params[:search]}%")

  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(id: :desc).page(params[:page])
    counts(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = '更新されました'
      redirect_to @user
    else
      flash.now[:danger] = '更新されませんでした'
      render :edit
    end
  end

  def destroy

  end


  def followings
    @user = User.find(params[:id])
    @followings = @user.followings.page(params[:page])
    counts(@user)
  end

  def followers
    @user = User.find(params[:id])
    @followers = @user.followers.page(params[:page])
    counts(@user)
  end

  def likes
    @user = User.find(params[:id])
    @likings = @user.likings.order(id: :desc).page(params[:page])
    counts(@user)
  end

  def search


  end

   private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :new_profile_picture, :image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_url(user, options = { size: 80 })
		 gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
	end
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>

    <div class="row mt-5">
        <div class="col-lg-12">
            <div class="form-kerri contact_form">
                <div id="message"></div>
                  <form method="post"  name="contact-form" >
                      <div class="row"><!-- ＊＊＊　画像選択　＊＊＊＊-->
                          <div class="col-lg-12">
                              <div class=" text-white mb-2">
                                <% if user.image? %>
														      <%= image_tag user.image.url,width: "400px",height: "auto" %>
														    <% else %>
														      <%= image_tag "/images/camera1.jpg", :size => '100x100' %>
														    <% end %>
                              </div>
                              <button type="button" class="btn btn-outline-secondary rounded-pill ">
                                <%= form.file_field :image, accept: 'image/jpeg,image/gif,image/png' %>
                              </button>
                          </div>
                      </div>
                      <div class="row"><!-- ＊＊＊　ユーザー　＊＊＊＊-->
                          <div class="col-lg-12">
                              <div class="text-white">
                                <%= form.label :name, "ユーザー名" %>
                              </div>
                              <div class="form-group mt-2">
                                <%= form.text_field :name %>
                              </div>
                          </div>
                      </div>
                      <div class="row"><!-- ＊＊＊　説明文　＊＊＊＊-->
                          <div class="col-lg-12">
                              <div class="text-white">
                                <%= form.label :email, "メールアドレス" %>
                              </div>
                              <div class="form-group mt-2">
                              	<%= form.text_field :email %>
                              </div>
                          </div>
                      </div>
                      <div class="row">
                          <div class="col-lg-12 text-right">
                              <div class= "d-flex align-items-center flex-column mb-5"><%= form.submit '更新', class: 'btn btn-light'%></div>
                              <div id="simple-msg"></div>
                          </div>
                      </div>
                  </form>
            </div>
        </div>
    </div>
<% end %>

app/views/users/_users.html.erb
<!-- 　ユーザー一覧　-->
<% if users.any? %>
  <ul class="list-unstyled pl-4">
    <% users.each do |user| %>
      <li class="media">
        <!-- ここにプロフィール画像のimage_tagを入れる --->
        <%# if user.profile_picture.attached?  %>
          <div><%#= image_tag user.profile_picture,width: "100%",height: "auto"%></div>
        <%# end  %>

    				<% if user.image? %>
              <div><%= image_tag user.image.url,width: "100%",height: "auto" %></div>
            <% else %>
              <div><%= image_tag "/images/camera1.jpg",width: "100%",height: "auto"  %></div>
            <% end %>

        <div class="media-body text-left pl-3">
          <div class="text-white">
            <%= user.name %>
          </div>
          <div>
            <p><%= link_to 'View profile', user_path(user) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

<style>
.media img {
  border-radius: 50%;  /* 角丸半径を50%にする(=円形にする) */
  width: 50px;  /* 縦横を同じ値にする */
  height: 50px;  /* 縦横を同じ値にする */
  object-fit: cover; /* 縦横比固定したまま上2つの縦横の範囲内に収まるように配置する */
}
</style>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<div class="d-flex align-items-center flex-column section">
    <h1 class="text-white mb-5" >ユーザー情報の編集</h1>

	  <div><%= render 'form', user: @user %></div>

		<div><%= link_to "Myページへ戻る", @user %></div>
</div>

app/views/users/followers.html.erb
<div class="row section">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
      <div class="card-body">
        <!-- ここにプロフィール画像を表示する処理を入れる-->
  				<% if @user.image? %>
            <%= image_tag @user.image.url,width: "100%",height: "auto" %>
          <% else %>
            <%= image_tag "/images/camera1.jpg",width: "100%",height: "auto"  %>
          <% end %>

          <% if current_user == @user %>
            <div class="mt-3"><%= link_to 'プロフィールの編集', edit_user_path(@user) , class: 'btn btn-info' %></div>
          <% end %>
      </div>
    </div>

  </aside>
  <div class="col-sm-8 text-white">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">Posts  <span class="badge badge-secondary"><%= @count_microposts %></span></a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">フォロー中  <span class="badge badge-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">フォロワー  <span class="badge badge-secondary"><%= @count_followers %></span></a></li>
			<li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">お気に入り一覧<span class="badge badge-secondary"><%= @count_likings%></span></a></li>
    </ul>
    <%= render 'users', users: @followers %>
  </div>

app/views/users/followings.html.erb
<div class="row section">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
      <div class="card-body">
      <!-- ここにプロフィール画像を表示する処理を入れる-->
				<% if @user.image? %>
          <%= image_tag @user.image.url,width: "100%",height: "auto" %>
        <% else %>
          <%= image_tag "/images/camera1.jpg",width: "100%",height: "auto"  %>
        <% end %>

        <% if current_user == @user %>
          <div class="mt-3"><%= link_to 'プロフィールの編集', edit_user_path(@user) , class: 'btn btn-info' %></div>
        <% end %>
      </div>
    </div>

  </aside>
  <div class="col-sm-8 text-white">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">Posts  <span class="badge badge-secondary"><%= @count_microposts %></span></a></li>
      <li class="nav-item text-white"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">フォロー中  <span class="badge badge-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">フォロワー  <span class="badge badge-secondary"><%= @count_followers %></span></a></li>
			<li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">お気に入り一覧<span class="badge badge-secondary"><%= @count_likings%></span></a></li>
    </ul>
    <%= render 'users', users: @followings %>
  </div>
</div>

app/views/users/index.html.erb
<!-- ユーザー検索  -->
<section class="section pl-2">
  <p class="text-white media-body text-left">ユーザー検索</p>
  <%= form_tag(users_path, :method => 'get' ) do %>
    <p class=" media-body text-left ">
    <%= text_field_tag :search %>
    <%= submit_tag 'Search', :name => nil %>
    </p>
  <% end %>
</section>

<%= render 'users', users: @users %>

app/views/users/likes.html.erb
<div class="row section">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
      <div class="card-body">
        <!-- ここにプロフィール画像を表示する処理を入れる-->
  				<% if @user.image? %>
            <%= image_tag @user.image.url,width: "100%",height: "auto" %>
          <% else %>
            <%= image_tag "/images/camera1.jpg",width: "100%",height: "auto"  %>
          <% end %>

          <% if current_user == @user %>
            <div class="mt-3"><%= link_to 'プロフィールの編集', edit_user_path(@user) , class: 'btn btn-info' %></div>
          <% end %>
      </div>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </aside>
  <div class="col-sm-8 text-white">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">Posts  <span class="badge badge-secondary"><%= @count_microposts %></span></a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">フォロー中 <span class="badge badge-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">フォロワー  <span class="badge badge-secondary"><%= @count_followers %></span></a></li>
     <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">お気に入り一覧<span class="badge badge-secondary"><%= @count_likings%></span></a></li>
    </ul>
    <%= render 'likes/like', likings: @likings %>
  </div>
</div>

app/views/users/new.html.erb
<div class="section">
      <div class="text-center text-light ">
      <h1>新規登録</h1>
      </div>

    <div class="row">
      <div class="col-sm-6 offset-sm-3 text-light">

        <%= form_with(model: @user, local: true) do |f| %>
            <%= render 'layouts/error_messages', model: f.object %>

          <div class="form-group">
            <%= f.label :name, 'Name' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :email, 'Email' %>
            <%= f.email_field :email, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password, 'Password' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>

    			<div class="form-group mb-5">
            <%= f.label :password_confirmation, 'Confirmation' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>

          <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
        <% end %>
      </div>
    </div>
</div>

app/views/users/show.html.erb
<!--  Myページ　 -->

<div class="row section" >
    <aside class="col-sm-4 " >
      <div class="card">
            <div class="card-header ">
              <h3 class="card-title"><%= @user.name %></h3>
            </div>
            <div class="card-body mt-123" style="">
              <!-- ここにプロフィール画像を表示する処理を入れる-->
                <%= form_for @user do |form| %>
            				<% if @user.image? %>
                      <%= image_tag @user.image.url,width: "100%",height: "auto" %>
                    <% else %>
                      <%= image_tag "/images/camera1.jpg",width: "100%",height: "auto"  %>
                    <% end %>
        				<% end %>

                <% if current_user == @user %>
                  <div class="mt-3"><%= link_to 'プロフィールの編集', edit_user_path(@user) , class: 'btn btn-info' %></div>
                <% end %>
            </div>
       </div>
      <%= render 'relationships/follow_button', user: @user %>
    </aside>
    <div class="col-sm-8 text-white  " >
          <ul class="nav nav-tabs nav-justified mb-3 ">
            <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">Posts  <span class="badge badge-secondary"><%= @count_posts %></span></a></li>
            <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">フォロー中  <span class="badge badge-secondary"><%= @count_followings %></span></a></li>
            <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">フォロワー<span class="badge badge-secondary"><%= @count_followers %></span></a></li>
            <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">お気に入り一覧<span class="badge badge-secondary"><%= @count_likings%></span></a></li>
          </ul>
          <div class="text-white d-flex flex-wrap ">
              <% @posts.each do |post| %>
                  <div class="d-flex flex-column ml-2 ">
                    <%= image_tag(post.image.url,width: "150",height: "auto") if post.image? %>
                    <div class="d-flex flex-row">
                      <p class="mr-3">
                        <%= post.title %>
                      </p>
                      <p>
                        <%= link_to 'Show', post %>
                      </p>
                     </div>
                   </div>
              <% end %>
           </div>
    </div>
</div