config/routes.rb
Rails.application.routes.draw do
  root "toppages#index"

	get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

	get 'signup', to: 'users#new'
	resources :users, only: [:index,:show, :new, :create, :edit, :update, :destroy] do
	  member do
      get :followings
      get :followers

      get :likes
    end
	end

	resources :posts, only: [:show, :new, :edit, :create, :update, :destroy] do
	  resources :comments, only: [:create, :destroy]
	end

  resources :relationships, only: [:create, :destroy]

  resources :likes, only: [:create, :destroy]


end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" >
    <ul class="mb-3  ">
      <% model.errors.full_messages.each do |message| %>
        <li style="list-style: none;"><%= message%></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-sm mb-4  fixed-top custom-nav sticky stickyadd">
    <a class="navbar-brand" href="/"><span>フォ</span><span>ト</span><span>シェ</span><span>ア</span></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon navbar-light bg-light m-auto p-auto">〓</span>
    </button>

    <div class="collapse navbar-collapse justify-content-end " id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item pt-2"><%= link_to 'Users', users_path, class: 'nav-link' %></li>
          <li class="nav-item pt-2"><%= link_to 'New Post', new_post_path ,class: 'nav-link'%></li>

          <li class="nav-item dropdown">

             <%# !-- 一時的にコメントアウト　cariawaveでherokuへプロフィール画像機能ができたら消す if current_user.profile_picture.attached?  %>
              <!--div class="profile_picture pt-1"><%#= image_tag current_user.profile_picture,width: "50",height: "50"%></div-->
             <%#end  %>
            <div class="profile_picture pt-1">
               <%= form_for current_user do |form| %>
            				<% if current_user.image? %>
                     <%= image_tag current_user.image.url,width: "50px",height: "50px" %>
                    <% else %>
                      <%= image_tag "/images/camera1.jpg",width: "50px",height: "50px"  %>
                    <% end %>
        			 <% end %>
      			 </div>
             <a href="#" class="nav-link dropdown-toggle pt-1" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item nav-link"><%= link_to 'My profile', user_path(current_user) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item nav-link"><%= link_to 'Logout', logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item pb-1"><%= link_to 'Signup', signup_path, class: 'nav-link' %></li>
          <li class="nav-item pb-1"><%= link_to 'Login', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
</nav>



<style>



.nav-link {
  position: relative;
  display: inline-block;
  transition: .3s;
}
.nav-link::after {
  position: absolute;
  bottom: 0;
  left: 0;
  content: '';
  width: 0;
  height: 1px;
  background-color: #FFFFFF	;
  transition: .3s;
}
.nav-link:hover {
  color: #FFFFFF;
}
.nav-link:hover::after {
  width: 100%;
}


.profile_picture {
  position: relative;
  display: inline-block;

}

.nav-item img {
  border-radius: 50%;  /* 角丸半径を50%にする(=円形にする) */
  width: 50px;  /* 縦横を同じ値にする */
  height: 50px;  /* 縦横を同じ値にする */
  object-fit: cover; /* 縦横比固定したまま上2つの縦横の範囲内に収まるように配置する */
}
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html  lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>フォトシェア</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>



  </head>

  <body>

  <%= render 'layouts/navbar' %>

  <%= yield %>


    <!-- ライトボックス     -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/js/lightbox.min.js" type="text/javascript"></script>

    <!-- 無限ループ  -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>


    <!-- Vue.jsの読み込み   -->
    <!--・toppages画像切り替え-->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>